
name: github actions demo 
on: [push]
jobs:
 test:
    runs on: ububtu-latest
steps: 
uses: actions /checkout@v2 
-run: echo "this job was automatically triggrred on $[github.event_name]"
-run: python main.py
